apiVersion: apps/v1
kind: Deployment
metadata:
  name: piazza-dvs-api-deployment
  labels:
    app: piazza-dvs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: piazza-dvs
  template:
    metadata:
      labels:
        app: piazza-dvs
    spec:
      containers:
      - name: piazza-dvs
        image: diego/bbk-acc-cw:1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: piazza-dvs
              key: MONGO_URI
        - name: TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: piazza-dvs
              key: TOKEN_SECRET